export const DOMElements = {
  grid: document.getElementById('grid'),
  toastContainer: document.getElementById('toast-container'),
  infoModal: {
    overlay: document.getElementById('info-modal'),
    closeBtn: document.querySelector('#info-modal .modal-close'),
    icon: document.getElementById('m-icon'),
    title: document.getElementById('m-title'),
    subtitle: document.getElementById('m-subtitle'),
    desc: document.getElementById('m-desc'),
    actionBtn: document.getElementById('m-action-btn'),
    dangerGroup: document.getElementById('m-danger-group'),
    confirmBtn: document.getElementById('m-confirm-btn'),
    cancelBtn: document.querySelector('#m-danger-group .modal-btn-cancel'),
    infoBtn: document.getElementById('m-info-btn'),
  },
  detailModal: {
    overlay: document.getElementById('detail-modal'),
    closeBtn: document.getElementById('d-m-close'),
    icon: document.getElementById('d-m-icon'),
    title: document.getElementById('d-m-title'),
    body: document.getElementById('d-m-body'),
  },
  menuModal: {
    overlay: document.getElementById('menu-modal'),
    closeBtn: document.querySelector('#menu-modal .modal-close'),
    resetBtn: document.getElementById('reset-game-btn'),
    collectionBtn: document.getElementById('collection-btn'),
    profileBtn: document.getElementById('profile-btn'),
    achievementsBtn: document.getElementById('achievements-btn'),
    collectionNotificationDot: document.getElementById('collection-notification-dot'),
    achievementsNotificationDot: document.getElementById('achievements-notification-dot'),
  },
  profileModal: {
    overlay: document.getElementById('profile-modal'),
    closeBtn: document.getElementById('p-m-close'),
    icon: document.getElementById('p-m-icon'),
    title: document.getElementById('p-m-title'),
    body: document.getElementById('p-m-body'),
  },
  achievementsModal: {
    overlay: document.getElementById('achievements-modal'),
    closeBtn: document.getElementById('ach-m-close'),
    body: document.getElementById('ach-m-body'),
  },
  collectionModal: {
    overlay: document.getElementById('collection-modal'),
    closeBtn: document.getElementById('c-m-close'),
    body: document.getElementById('c-m-body'),
    footer: document.getElementById('c-m-footer'),
  },
  level: {
    bar: document.getElementById('level-bar'),
    text: document.getElementById('player-level'),
    score: document.getElementById('score-text'),
    container: document.querySelector('.level-container'),
  },
  energy: {
    value: document.getElementById('energy-val'),
    container: document.querySelector('.energy-container'),
  },
  coins: {
    value: document.getElementById('coins-val'),
    container: document.querySelector('.coins-container'),
  },
  menuBtn: document.querySelector('.menu-btn'),
  menuNotificationDot: document.getElementById('menu-notification-dot'),
  ordersList: document.getElementById('orders-list'),
  rewardQueuePanel: document.getElementById('reward-queue-panel'),
};