export const DOMElements = {
  grid: document.getElementById('grid'),
  startScreen: document.getElementById('start-screen-overlay'),
  toastContainer: document.getElementById('toast-container'),
  infoModal: {
    overlay: document.getElementById('info-modal'),
    closeBtn: document.querySelector('#info-modal .modal-close'),
    icon: document.getElementById('m-icon'),
    title: document.getElementById('m-title'),
    subtitle: document.getElementById('m-subtitle'),
    desc: document.getElementById('m-desc'),
    actionBtn: document.getElementById('m-action-btn'),
    dangerGroup: document.getElementById('m-danger-group'),
    confirmBtn: document.getElementById('m-confirm-btn'),
    cancelBtn: document.querySelector('#m-danger-group .modal-btn-cancel'),
    infoBtn: document.getElementById('m-info-btn'),
  },
  detailModal: {
    overlay: document.getElementById('detail-modal'),
    closeBtn: document.getElementById('d-m-close'),
    icon: document.getElementById('d-m-icon'),
    title: document.getElementById('d-m-title'),
    body: document.getElementById('d-m-body'),
    desc: document.getElementById('d-m-desc'),
    extraContent: document.getElementById('d-m-extra-content'),
  },
  menuModal: {
    overlay: document.getElementById('menu-modal'),
    closeBtn: document.querySelector('#menu-modal .modal-close'),
    resetBtn: document.getElementById('reset-game-btn'),
    collectionBtn: document.getElementById('collection-btn'),
    settingsBtn: document.getElementById('settings-btn'),
    profileBtn: document.getElementById('profile-btn'),
    achievementsBtn: document.getElementById('achievements-btn'),
    collectionNotificationDot: document.getElementById('collection-notification-dot'),
    achievementsNotificationDot: document.getElementById('achievements-notification-dot'),
    storyBtn: document.getElementById('story-btn'),
    storyNotificationDot: document.getElementById('story-notification-dot'),
    tutorialBtn: document.getElementById('tutorial-btn'),
  },
  settingsModal: {
    overlay: document.getElementById('settings-modal'),
    closeBtn: document.getElementById('s-m-close'),
    body: document.getElementById('s-m-body'),
  },
  profileModal: {
    overlay: document.getElementById('profile-modal'),
    closeBtn: document.getElementById('p-m-close'),
    icon: document.getElementById('p-m-icon'),
    title: document.getElementById('p-m-title'),
    body: document.getElementById('p-m-body'),
  },
  achievementsModal: {
    overlay: document.getElementById('achievements-modal'),
    closeBtn: document.getElementById('ach-m-close'),
    body: document.getElementById('ach-m-body'),
  },
  collectionModal: {
    overlay: document.getElementById('collection-modal'),
    closeBtn: document.getElementById('c-m-close'),
    body: document.getElementById('c-m-body'),
    footer: document.getElementById('c-m-footer'),
  },
  level: {
    bar: document.getElementById('level-bar'),
    text: document.getElementById('player-level'),
    score: document.getElementById('score-text'),
    container: document.querySelector('.level-container'),
  },
  energy: {
    value: document.getElementById('energy-val'),
    container: document.querySelector('.energy-container'),
  },
  coins: {
    value: document.getElementById('coins-val'),
    container: document.querySelector('.coins-container'),
  },
  menuBtn: document.querySelector('.menu-btn'),
  menuNotificationDot: document.getElementById('menu-notification-dot'),
  ordersList: document.getElementById('orders-list'),
  rewardQueuePanel: document.getElementById('reward-queue-panel'),
  bgMusic: document.getElementById('bg-music'),
  sfxMerge: document.getElementById('sfx-merge'),
  sfxMergeLevels: {
    2: document.getElementById('sfx-merge-lvl2'),
    3: document.getElementById('sfx-merge-lvl3'),
    4: document.getElementById('sfx-merge-lvl4'),
    5: document.getElementById('sfx-merge-lvl5'),
    6: document.getElementById('sfx-merge-lvl6'),
    7: document.getElementById('sfx-merge-lvl7'),
  },
  sfxSwap: document.getElementById('sfx-swap'),
  sfxSpawn: document.getElementById('sfx-spawn'),
  sfxClaimReward: document.getElementById('sfx-claim-reward'),
  sfxGeneratorSpawn: document.getElementById('sfx-generator-spawn'),
  sfxOrderComplete: document.getElementById('sfx-order-complete'),
  sfxCoin: document.getElementById('sfx-coin'),
  sfxDragStart: document.getElementById('sfx-drag-start'),
  sfxOrderReady: document.getElementById('sfx-order-ready'),
  // Добавьте новый объект для модального окна сюжета
  storyModal: {
    overlay: document.getElementById('story-modal'),
    closeBtn: document.getElementById('st-m-close'),
    title: document.getElementById('st-m-title'),
    body: document.getElementById('st-m-body'),
    actions: document.getElementById('st-m-actions'),
  },
  tutorialModal: {
    overlay: document.getElementById('tutorial-modal'),
    body: document.getElementById('tut-m-body'),
    closeBtn: document.getElementById('tut-m-close'),
    confirmBtn: document.getElementById('tutorial-close-btn')
  },
  storySelectionModal: {
    overlay: document.getElementById('story-selection-modal'),
    closeBtn: document.getElementById('story-selection-close'),
    body: document.getElementById('story-selection-body'),
  },

};